spring:
  application:
    name: FinCiclo

  datasource:
    url: jdbc:postgresql://localhost:5432/proyecto_db
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
